services:
  todo-api:
    build:
      context: "./todo-api"
      dockerfile: Dockerfile
    image: "danilocristo/todo-api:0.0.1"
    container_name: todo-api
    ports:
      - 5000:5000
    networks:
      - kong_learning
    depends_on:
      rabbitmq:
        condition: service_healthy
  scheduler-api:
    build:
      context: "./scheduler-api"
      dockerfile: Dockerfile
    image: "danilocristo/scheduler-api:0.0.1"
    container_name: scheduler-api
    ports:
      - 3000:3000
    networks:
      - kong_learning
    depends_on:
      rabbitmq:
        condition: service_healthy
  rabbitmq:
    image: rabbitmq
    container_name: rabbitmq
    ports: 
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=fitz
      - RABBITMQ_DEFAULT_PASS=fitz
    networks:
      - kong_learning
    healthcheck:
      test: rabbitmq-diagnostics -q ping
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.2
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - kong_learning
  rank-api:
    build:
      context: "./rank-api"
      dockerfile: Dockerfile
    image: "danilocristo/rank-api:0.0.1"
    container_name: rank-api
    ports:
      - 8080:8080
    networks:
      - kong_learning

  kafka:
    image: confluentinc/cp-kafka:7.3.2
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - kong_learning
  kong:
    image: kong/kong-gateway:latest
    container_name: kong
    ports:
      - 8000:8000
    volumes:
      - ./kong/kong.yaml:/usr/local/kong/declarative/kong.yaml
    environment:
      KONG_DATABASE: off
      KONG_DECLARATIVE_CONFIG: /usr/local/kong/declarative/kong.yaml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stdout
      KONG_ADMIN_ERROR_LOG: /dev/stdout
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
    networks:
      - kong_learning

networks:
  kong_learning:
    name: "kong_learning"
    driver: bridge
